### ISSUE TITLE
Parameter Missing in Mandrill.EmailMessage: merge_language

### ISSUE THREAD

**Issue by virajsanghavi** [shawnmclean/Mandrill-dotnet#104]
Hi,

Mandrill api support 2 language when evaluating merge tags, either mailchimp or handlebars.
I didn't found any parameter for merge language under Mandrill.EmailMessage class.

Is there another way to specify merge language ?
If not can you please add ?

Regards,
Viraj Sanghavi

**Comment by roryprimrose** [comment]
This was added via #105
