### ISSUE TITLE
Add support for new handlebars template support

### ISSUE THREAD

**Issue by roryprimrose** [shawnmclean/Mandrill-dotnet#105]
Mandrill has published support for handlebars template syntax. See http://blog.mandrill.com/handlebars-for-templates-and-dynamic-content.html

There is a new switch required on EmailMessage (merge_language). It's not clear yet without playing with the new template support about where the data comes from. Presumably it is from global_merge_vars and merge_vars

**Comment by roryprimrose** [comment]
Yep, data comes from merge variables - http://blog.mandrill.com/handlebars-for-templates-and-dynamic-content.html#examples. Seems like the only thing required to support this via this project is to support the new merge_language property.

**Comment by roryprimrose** [comment]
I have tested this using my integration test suite that tests my own templates. Both handlebars and mailchimp syntax (tested via not specifying the value) work as expected.

**Comment by christianhxc** [comment]
@roryprimrose do you have by any chance an example of loop in a template like the one in the post you put here? I didn't find any in your repo

**Comment by roryprimrose** [comment]
That's not implemented yet. My PR was to support template syntax selection. Supporting collections and complex types is still outstanding.

**Comment by cerberusaeon** [comment]
Is there a working example of this functionality?  I'd like a complete json object with handlebars in the message content.
