### ISSUE TITLE
Update variable support to allow for objects as well as strings

### ISSUE THREAD

**Issue by roryprimrose** [shawnmclean/Mandrill-dotnet#107]
The new handlebars support allows for object graphs and collections to be bound to the handlebars template. The EmailMessage class however only allows for strings to be added as variables.

One alternative here is to add an overload that takes object as the merge variable. The logic of this overload can then convert that to a JSON string and forward to the string merge variable method.

**Comment by shawnmclean** [comment]
Hey @roryprimrose , I can't do any dev work until next week as I am out of a machine to work with, if you can implement it and do a PR as you did earlier, I can accept it and have teamcity push it to nuget

**Comment by roryprimrose** [comment]
I'll see if I can get to it. I only need simple fields ATM. I did find a bug with the previous PR which I'm fixing up now.

**Comment by roryprimrose** [comment]
This hasn't been implemented yet. Was closing this intentional?

**Comment by shawnmclean** [comment]
Oh sorry, I thought you did.

**Comment by Stephen-McDowell** [comment]
I'm a TFS guy so contributing to this by doing a PR is beyond me.  Changing the content property type to "object" is all that is required to make this work with handlebars.  BTW nice work on this project! 

    public struct merge_var
    {
        #region Fields
        /// <summary>
        ///     The content.
        /// </summary>
        public object content;    // Changed from string to object

        /// <summary>
        ///     The name.
        /// </summary>
        public string name;
        #endregion
    }

**Comment by kiquenet** [comment]
Any full sample (Integration Tests) using Merge variables like this:

***http://stackoverflow.com/questions/23998219/mandrill-editable-template-mcedit-link-href***
