### ISSUE TITLE
Getting error in Mandrill.JSON

### ISSUE THREAD

**Issue by klanda20** [shawnmclean/Mandrill-dotnet#110]
Hello,

I'm getting the following error on every call I try:

An exception of type 'System.TypeInitializationException' occurred in Mandrill.dll but was not handled in user code

Additional information: The type initializer for 'Mandrill.JSON' threw an exception.

It's happening here:

public Task<T> PostAsync<T>(string path, dynamic data) where T : new()
        {
            Task<IRestResponse> post = this.PostAsync(path, data);

            return post.ContinueWith(
                p =>
                    {
                        var t = JSON.Parse<T>(p.Result.Content);   <-- this line
                        return t;
                    },
                TaskContinuationOptions.ExecuteSynchronously);
        }

Here is my code (vb.net)

Dim mapi As New MandrillApi("XXXXXXXXXXXXXXXXXXXX")

Dim ui As UserInfo = mapi.UserInfo

Any ideas?

**Comment by klanda20** [comment]
My problem was that my project already reference Newtonsoft.JSON and the versions were colliding.

**Comment by ridespirals** [comment]
I'm having a similar issue, we are using version `2.4.1.0` which states the dependencies are `>= 6.0.6`, but we have upstream projects explicitly using Newtonsoft.Json version `9.0.1`. When trying to use the Mandrill api, I get an error about not finding Newtonsoft.Json version 7.0.1. How would I go about resolving this? I cannot downgrade the version of Newtonsoft.Json we are using.

**Comment by ridespirals** [comment]
Nevermind. turns out the issue was on my end. We had a binding redirect set up for Newtonsoft.Json pointing to version 7. Updating that to point to 9 solved the issue.
