### ISSUE TITLE
Casting an array of Attachments to IEnumerable<email_attachmen>()

### ISSUE THREAD

**Issue by valokafor** [shawnmclean/Mandrill-dotnet#117]
I am  trying to convert an email method that using Mandrill SMTP to API and an array of attachment is passed to this method  like so:

public string sendEmail(string sBody, string sSubject, string sTo,  params Attachment[] attachments)
{
 MandrillApi api = new MandrillApi("xxxxx-xxxx-xxxx");
 var newAttachments = new List<email_attachment>();

                    var emailMessage = new EmailMessage();
                    foreach (Attachment attachment in attachments)
                    {
                        newAttachments.Add((email_attachment)attachment);

                    }
                    emailMessage.attachments = newAttachments;
                    
}

I am trying to pass the array of attachments I recieved via this method call to the attachment property of the emailMessage. I cannot change the signature of this method because it has been used lots pf places in the project.

Please can someone point me in the right direction>

**Comment by pylenius** [comment]
Hi, 

I didn't test this yet but this could work.
That line "type = attachment.ContentType.MediaType," is just my best guess...

            var newAttachaments = new List<email_attachment>();
            foreach (var attachment in attachments)
            {
                var ms = new MemoryStream();
                attachment.ContentStream.CopyTo(ms);
                var a = new email_attachment
                {
                    name = attachment.Name,
                    type = attachment.ContentType.MediaType,
                    content = Convert.ToBase64String(ms.GetBuffer(), 0, (int)ms.Length)
                };
                newAttachaments.Add(a);
            }

**Comment by valokafor** [comment]
Thanks, that worked
