### ISSUE TITLE
Add Strong Name to your DLL

### ISSUE THREAD

**Issue by fhebert33** [shawnmclean/Mandrill-dotnet#121]
If possible add a strong name to your dll.  This way we could use your reference in a SSIS project.  Script task in SSIS is VSTA project and you need strong name identification for all your DLL that you use.
And use RestSharpShigned  (http://www.nuget.org/packages/RestSharpSigned) in your project.
![restsharp strongname](https://cloud.githubusercontent.com/assets/10655028/6833870/88a11ccc-d306-11e4-8b2b-f2c6a3359d00.jpg)

**Comment by shawnmclean** [comment]
Will be reverting the current signed assembly and creating a new separate package for signed assembly. See issue #125.

**Comment by shawnmclean** [comment]
Based on this thread: https://github.com/octokit/octokit.net/issues/405, it was suggested that you sign the assembly yourself. Feel free to fork it and sign it.
