### ISSUE TITLE
PostAsync exception handling

### ISSUE THREAD

**Issue by asahellgren** [shawnmclean/Mandrill-dotnet#123]
Hello!
We have just recently started to use mandrill api and your mandrill-dotnet solution to send emails and encountered an error this weekend when an email was sent. We got an error in SetException in PostAsync, where the exception parameter passed in was null. We looked through the code in PostAsync and we would like to understand some reasoning behind the exception handling.

According to Mandrill API documentation, anything that is not HTTP 200 OK, can be treated as an error.

According to RestSharp documentation, the ErrorException will be set when there is a transport error, not set for other known HTTP status codes.

If there is a known HTTP status code sent back from RestSharp, current implementation in PostAsync will not have the response.ErrorException set and thus SetException will throw parameter null exception.

We suggest that there is a null check for response.ErrorException and if it is null, then throw a Mandrill exception.

Thankful for any feedback. We are open to update the code ourselves and make a pull request.

**Comment by shawnmclean** [comment]
Hey, sure, go right ahead with a PR!
