### ISSUE TITLE
No ConfigureAwait(false) on async library calls

### ISSUE THREAD

**Issue by michaelmsm89** [shawnmclean/Mandrill-dotnet#126]
Methods such as SendMessageAsync do not configure async calls to not continue on the captured context. This causes issues for applications such as web apps, where you do not want to use the same thread context to continue with the execution after the async method returns. This forces users of the library to call methods in the following way:
```C#
var result = await _api.SendMessageAsync(mandrillEmail).ConfigureAwait(false);
```
or they never return to the next line of code.

**Comment by shawnmclean** [comment]
Could you provide some more details of what is expected please?

**Comment by michaelmsm89** [comment]
I would expect the library to use Task.ConfigureAwait(false) for any async calls that it makes, so that the user of the library would not have to. 

Have a look at this blog post by Stephen Cleary which explains in detail the benefit of doing this.
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by shawnmclean** [comment]
So the new code does not block from all levels in the process. This should fix the deadlock issue.

I have not yet added `ConfigureAwait(false)` as yet, doing some more research on it.

**Comment by pebezo** [comment]
Maybe this would help with your research: http://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Async-library-methods-should-consider-using-Task-ConfigureAwait-false-?wt.mc_id=EntriesInArea
