### ISSUE TITLE
SearchResult doesnt contain OpenDetails

### ISSUE THREAD

**Issue by courtzzz** [shawnmclean/Mandrill-dotnet#131]
Hi there,

Im executing the api.Info method but unfortunately SearchResult doesnt contain the object for OpenDetails. I see MessageInfo.cs does? Im confused. How do i access this for a message?

**Comment by courtzzz** [comment]
Wow. What a quick response. How do i get these changes through Nuget?

**Comment by shawnmclean** [comment]
Hey @courtzzz, we're currently doing a major refactor related to #127 that will break existing code. Hopefully we can complete and push it by next week. 

The NuGet version 1.3.1 will be the last version supported before the breaking changes. Maybe I started this whole migration thing wrong by not creating a branch for the new version.

**Comment by courtzzz** [comment]
Thanks @shawnmclean. So I should hold off getting latest through Github? For instance i just got the latest from github and it seems that SendMessage no longer takes a templatename.... 

Or should i get latest and begin my refactor?

**Comment by shawnmclean** [comment]
@courtzzz, you can get the latest from github and start refactoring against that code. Some things may change by the time its on NuGet, such as the Request models may have constructors that will be used to force setting required properties.

What is on github may be unstable for production, I'm trying not to break existing tests and add more as I go along with the refactor.
