### ISSUE TITLE
AddHeader getting error

### ISSUE THREAD

**Issue by educosta** [shawnmclean/Mandrill-dotnet#133]
Hi,

If I use AddHeader method I getting the error Cannot apply indexing with [] to an expression of type 'System.Dynamic.ExpandoObject'

**Comment by shawnmclean** [comment]
Thanks, I figured this would give an error. I'll fix it and add some tests for it in a few hours.

**Comment by shawnmclean** [comment]
Fixed in `2.0.3` nuget package.
