### ISSUE TITLE
Any plans to support .NET Core in ASP.NET 5 ?

### ISSUE THREAD

**Issue by radenkozec** [shawnmclean/Mandrill-dotnet#139]
Any plans to support .NET Core in ASP.NET 5 ?

**Comment by shawnmclean** [comment]
It depends on if Flurl.Http will support it. If not, I can swap it out for a portable http client. If anyone wants to, they can do this.

**Comment by shawnmclean** [comment]
Flurl removed, now looking into supporting .NET Core.

**Comment by ctolkien** [comment]
+1 on this - as .Net Core just hit RC1

**Comment by ctolkien** [comment]
Will put my hand up for this one?

Already got a bit carried away and got started..

![image](https://cloud.githubusercontent.com/assets/515955/11291742/17d04de8-8f98-11e5-88f7-603f4da18ec4.png)

**Comment by mmillican** [comment]
Would definitely be interested in seeing this supported since `System.Net.Mail` has not been ported to corefx, and it doesn't sound like it will be for a while.

@ctolkien curious - how's it coming along?

**Comment by ctolkien** [comment]
@mmillican it builds and runs on .net core with minimal changes. What I'm more coming to grips with is the new project system - ensuring we can still build for regular .Net, running tests, etc.

I'll do some more digging tonight and will fire a PR off for visibility - even if not ready to merge.

**Comment by shawnmclean** [comment]
@ctolkien did you create those `.xproj` and `project.json` files manually?

**Comment by ctolkien** [comment]
Xproj - no, that would be VS. Project.json, was probably made by hand however?
