### ISSUE TITLE
Waits forever on any call to Mandrill API

### ISSUE THREAD

**Issue by Lexa1983** [shawnmclean/Mandrill-dotnet#140]
Using your lib without async/await.
Stuck on this line - waits forever
```
var results = api.SendMessage(request).Result;
```
What I'm doing wrong?
Thanks

**Comment by TimS-** [comment]
I am getting the same - no response at all, have tried with and without async

**Comment by Lexa1983** [comment]
I resolved it.
You must use ConfigureAwait(false) and put async on level up to the controllers action.
For example:

```
public async Task<ActionResult> YourActionMethod()
{
    await AnotherMethod();
//    return result
}

void async AnotherMethod()
{
    var result = await MandrillApi.SendMessge(...).ConfigureAwait(false);
}
```

**Comment by danielkatz** [comment]
Had the same problem while using mandrill from synchronous code in webforms app.
Since in webforms you cannot make the whole stack async as @Lexa1983 suggested, i found a working solution here: http://stackoverflow.com/a/25097498

**Comment by shawnmclean** [comment]
Update 2.1.2.0 should fix this. Try it and tell me if it works.

**Comment by thoxx** [comment]
I have the some problem with 2.1.4.0
```C#
public async Task SendAsync(IdentityMessage message)
{
	MandrillApi api = new MandrillApi("XXX");

    /*create mail, template content, etc. */
	[...]

	SendMessageTemplateRequest templateRequest = new SendMessageTemplateRequest(mail, templateName, new List<Mandrill.Models.TemplateContent> { content });
	try
	{
		var result = await api.SendMessageTemplate(templateRequest);
	}
	catch (Exception ex)
	{
		Elmah.ErrorLog.GetDefault(null).Log(new Error(ex) { User = message.Destination });
	}
}
```

An exception occurs after waiting 100 seconds at **api.SendMessageTemplate()** :
*Post failed /messages/send-template.json with status  and content ''*

The call does not appear in mandrill API logs (under "Last 100 Succeeded/Failed API Calls").

Any hints?

**Comment by Lexa1983** [comment]
As I said before, you need await this method up to the Consoller's action (to have action async as well).
Also make sure you have ConfigureAwaiter(false) on every api call.

**Comment by thoxx** [comment]
The controller awaits the send method. Setting ConfigureAwaiter(false) makes no difference.
My code (I'm using Identity Framework 2.0):
```C#
[HttpPost]
[AllowAnonymous]
[ValidateAntiForgeryToken]
public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
{
	/* check user etc */
	[...]
	var code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
	var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
	try
	{
		await UserManager.SendEmailAsync(user.Id, "ForgotPassword", callbackUrl);
		/* this calls SendAsync from EmailService */
	}
	[...]
}
```

```C#
public class EmailService : IIdentityMessageService
{
	public async Task SendAsync(IdentityMessage message)
	{
		[...]
		/* see code from last post */
		var result = await api.SendMessageTemplate(templateRequest).ConfigureAwait(false);
		[...]
	}
}
```

Any hints?

**Comment by Lexa1983** [comment]
async/await seems OK. You better check issues with API call to Mandrill.
I also experiences some problems with sending message template.
Check if some simple stupit async call to Mandrill succeed.

**Comment by jojogeyer** [comment]
Thank you @danielkatz . The AsyncHelper works like a charm. Using WinForms.
