### ISSUE TITLE
Unable to find version '2.0.3.0' of package 'Mandrill'.

### ISSUE THREAD

**Issue by Korijn** [shawnmclean/Mandrill-dotnet#142]
Continuous Deployment on Azure started throwing this error today. Having a hard time reproducing it. Anyone else? Any thoughts?

**Comment by shawnmclean** [comment]
How are you doing CD with Azure? Is the reference set to copy the output of the dll?

**Comment by Korijn** [comment]
I should have mentioned that NuGet is throwing this error. I haven't touched the reference settings. 

The reference in `packages.config`:

`<package id="Mandrill" version="2.0.3.0" targetFramework="net451" />`

When the build starts, the `nuget restore` command is executed and that throws the following error (from the log):

```
All packages listed in packages.config are already installed.
Unable to find version '2.0.3.0' of package 'Mandrill'.
Failed exitCode=1, command=nuget restore "D:\home\site\repository\<project>.sln"
An error has occurred during web site deployment.
```

Screenshots:

![mandrill_ref](https://cloud.githubusercontent.com/assets/1882046/7830617/4c907e7e-044f-11e5-93ae-fddb8a20f941.jpg)

![mandrill_nuget](https://cloud.githubusercontent.com/assets/1882046/7830620/4dc0fd8c-044f-11e5-9b6b-5df8e41f5192.jpg)

**Comment by Korijn** [comment]
Well... after not changing anything and two days, things started building again. Same revision. WEIRD! Thanks for your time anyway. :)
