### ISSUE TITLE
Not working with Flurl Version=1.0.8.0

### ISSUE THREAD

**Issue by babakarj** [shawnmclean/Mandrill-dotnet#146]
By upgrading Flurl from 1.0.7.0 to 1.0.8.0 we get this error:

```
System.IO.FileNotFoundException
       HResult=-2147024894
       Message=Could not load file or assembly 'Flurl, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
       Source=Mandrill
       FileName=Flurl, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null
       FusionLog==== Pre-bind state information ===
LOG: DisplayName = Flurl, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///D:/----/
LOG: Initial PrivatePath = D:\----\bin
Calling assembly : Mandrill, Version=2.1.4.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\----\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

       StackTrace:
            at Mandrill.MandrillApi.<Post>d__2c`1.MoveNext()
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
            at Mandrill.MandrillApi.Post[T](String path, RequestBase data)
            at Mandrill.MandrillApi.<SendMessageTemplate>d__22.MoveNext()
       InnerException: 
```

**Comment by shawnmclean** [comment]
Did this get sorted out?

**Comment by babakarj** [comment]
@shawnmclean How? Any new update?

**Comment by shawnmclean** [comment]
@babakarj Its not finding the file when trying to load the assembly. Is copy local set to true on the reference? Otherwise, I'm not sure, it works for me and the build server.

**Comment by Sumomannen** [comment]
When I install the latest nuget I also get this error, on both flurl.http with needs to be 6.0.0.0 and flurl with needs to be 1.0.7.0. When I downgrade both this nugets it works to send mails.

**Comment by webprofusion-chrisc** [comment]
Hi, seeing this also after updating to latest version of Mandrill.net. The Flurl dll is setup to copy local=true but is not being included when you publish to the remote server. This previously used to happen with RestSharp as well, so I think it's the way your referencing it as a nuget dependency somehow. The problem for users it that they don't see this until they publish to a remote server (in my case, production!).

**Comment by dylandhall** [comment]
Also having this issue - we have downgraded Flurl DLLs in the meantime.

**Comment by shawnmclean** [comment]
We're working to remove flurl. I've gotten a PR that switched to `HttpClient` but needs some refactoring across all other requests.

**Comment by dylandhall** [comment]
Thanks Shawn, will keep an eye out

**Comment by babakarj** [comment]
@shawnmclean Thanks, we set our CI to handle it for a while. :)

**Comment by shawnmclean** [comment]
This issue should be fixed in v 2.2.1.

Sorry for the trouble guys.

**Comment by dylandhall** [comment]
Thanks for attending to this! :+1:

**Comment by Sumomannen** [comment]
Thanks guys!

**Comment by tmenier** [comment]
Wish I'd seen a couple months ago, sorry to hear Flurl was the source of some headaches. I'm sure it's too late for your project but if anyone has suggestions for how similar issues could be prevented on my end please do let me know, I'd definitely like Flurl to be viable for use in API wrappers.
