### ISSUE TITLE
SendMessage - Waiting for activation (result) issue

### ISSUE THREAD

**Issue by rgino0002** [shawnmclean/Mandrill-dotnet#148]
Below is a very basic method I wrote to test the API. It keeps returning {Id = 1, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"}. Nothing is registering in the API logs. As you can see below I am not calling the SendMessage async which might be the issue within itself. 

I am converting over to this Lib from the mcapi.net lib which we have been using for quite some time. Any help would be highly appreciated. Thanks.

    public void testEmail()
    {
        EmailMessage msg = new EmailMessage();
        List<EmailAddress> recips = new List<EmailAddress>();
        recips.Add(new EmailAddress(MY_EMAIL, "me"));
        msg.Html = "test message body";
        msg.Subject = "Howdy";
        msg.To = recips;
        
        var result = mandrillAPI.SendMessage(new Mandrill.Requests.Messages.SendMessageRequest(msg));     
    }

**Comment by shawnmclean** [comment]
Hi @rgino0002,

All API methods are async.

This means you'll need to convert your method to support async and await. You'll eventually end up with a method looking like:

    public asynt Task testEmail()
    {
        EmailMessage msg = new EmailMessage();
        List<EmailAddress> recips = new List<EmailAddress>();
        recips.Add(new EmailAddress(MY_EMAIL, "me"));
        msg.Html = "test message body";
        msg.Subject = "Howdy";
        msg.To = recips;

        var result = await mandrillAPI.SendMessage(new Mandrill.Requests.Messages.SendMessageRequest(msg));     
    }

**Comment by rgino0002** [comment]
Okay that was it, my test email sent out. 

Thank you very much! Closing this out.

**Comment by haobh** [comment]
3e5yrty
