### ISSUE TITLE
How can we get the list of Emails that were sent from a SUBACCOUNT in Mandrill using mandrill-dotnet version 1.3.1.0

### ISSUE THREAD

**Issue by AkshayOptionM** [shawnmclean/Mandrill-dotnet#170]
Hi Shawn can you please advice me if we can get the list of mails sent through mandrill from a specific subaccount. I need the complete details like sender email id, recipient email id, sent time and date, total number of mails sent etc. Please advice.

thanks in advance

**Comment by shawnmclean** [comment]
Hi @AkshayOptionM, this might be a question for the Mandrill team/support.
