### ISSUE TITLE
Publish DNX to Nuget

### ISSUE THREAD

**Issue by shawnmclean** [shawnmclean/Mandrill-dotnet#171]
- [x] Configure DNX for Source
- [ ] Travis versions Library
- [ ] Publish DNX Library to NuGet via Travis
- [ ] Add DNX project for Tests
- [ ] Configure Travis to run DNX Tests

**Comment by ctolkien** [comment]
With .Net Core RC2 (expected this month) comes the new `dotnet` cli experience and the removal of `DNX`. I'd put these bits on hold until the dust settles with RC2.
