### ISSUE TITLE
HttpClient instantiated for every request

### ISSUE THREAD

**Issue by dpwilson** [shawnmclean/Mandrill-dotnet#174]
MandrillApi.Post creates a new instance of the HttpClient for ever request. This can result in a significant overhead and performance loss when making many requests. Ideally the HttpClient would be held open for the life of the application which is how it was intended to be used by the HttpClient team at MS.

http://codereview.stackexchange.com/questions/69950/single-instance-of-reusable-httpclient

**Comment by shawnmclean** [comment]
Released in [3.1.0](https://github.com/shawnmclean/Mandrill-dotnet/releases/tag/3.1.0)
