### ISSUE TITLE
Cc and Bcc Not working as expected

### ISSUE THREAD

**Issue by frostymarvelous** [shawnmclean/Mandrill-dotnet#178]
Hi, first, thanks for the work and effort. I really like how streamlined it all is.

My problem comes from cc and bcc.

            var msg = new EmailMessage
            {
                AutoText = true,
                AutoHtml = true,
                Subject = email.Subject,
                FromEmail = email.From.Address,
                FromName = email.From.DisplayName,
                To = email.To.Select(t => new EmailAddress(t.Address, t.User, "to"))
                    .Concat(email.Cc.Select(c => new EmailAddress(c.Address, c.User, "cc")))
                    .Concat(email.Bcc.Select(b => new EmailAddress(b.Address, b.User, "bcc")))
                
            };

However, I find that instead of having the cc user cc'ed, it comes as a completely separate email.

Is there something I am doing wrong?

**Comment by mhallin79** [comment]
Hi frostymarvelous,

You need to set PreserveRecipients to true.

Hope this helps!

Cheers!

Mikael

**Comment by frostymarvelous** [comment]
Thanks a lot. That worked.
