### ISSUE TITLE
Template variables & line breaks, CLRF

### ISSUE THREAD

**Issue by horseyhorsey** [shawnmclean/Mandrill-dotnet#182]
Hi Shaun

How is this possible to add into a template variable?:

eg, `string templateString = "I am a string.\r\n And a new line return."`

Tried with Enviroment.newLine too but no joy....

Any tips to progress or other methods to use.

Cheers
Dave

**Comment by shawnmclean** [comment]
Sorry, I'm not sure. Mandrill templates are html I think, `<br />` might work. I know my suggestion is extremely late, sorry :(
