### ISSUE TITLE
Exe crash

### ISSUE THREAD

**Issue by MikeOtown** [shawnmclean/Mandrill-dotnet#185]
Attempting to Step Into this line...

 List<Mandrill.Models.EmailResult> res = await mand.SendMessageTemplate(req);

gives only...

The thread 0x2224 has exited with code 0 (0x0).
The thread 0x2228 has exited with code 0 (0x0).
The thread 0x2904 has exited with code 0 (0x0).
Step into: Stepping over property 'System.Runtime.CompilerServices.TaskAwaiter.get_IsCompleted'.  To step into properties, go to Tools->Options->Debugging and uncheck 'Step over properties and operators (Managed only)'.
The thread 0x4200 has exited with code 0 (0x0).
The thread 0x2470 has exited with code 0 (0x0).
The program '[19824] xxx.vshost.exe' has exited with code 0 (0x0).

what is happening?

**Comment by MikeOtown** [comment]
If I remove the "await", the app doesn't crash but no email is sent.

In Fiddler, this is the only Request and there is no Response Body...

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.1 (TLS/1.0)
Random: 58 A4 C1 45 90 B1 77 8D DD FA CE 43 AC B4 5F 48 43 8E 26 76 C6 BB 0E 08 62 D0 43 D6 BA A2 A1 96
"Time": 2/1/2007 3:27:04 AM
SessionID: empty
Extensions: 
	server_name	mandrillapp.com
	elliptic_curves	secp256r1 [0x17], secp384r1 [0x18]
	ec_point_formats	uncompressed [0x0]
	SessionTicket	empty
	extended_master_secret	empty
	renegotiation_info	00
Ciphers: 
	[C00A]	TLS1_CK_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
	[C009]	TLS1_CK_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
	[C014]	TLS1_CK_ECDHE_RSA_WITH_AES_256_CBC_SHA
	[C013]	TLS1_CK_ECDHE_RSA_WITH_AES_128_CBC_SHA
	[0039]	TLS_DHE_RSA_WITH_AES_256_SHA
	[0033]	TLS_DHE_RSA_WITH_AES_128_SHA
	[0035]	TLS_RSA_AES_256_SHA
	[002F]	TLS_RSA_AES_128_SHA
	[000A]	SSL_RSA_WITH_3DES_EDE_SHA
	[0038]	TLS_DHE_DSS_WITH_AES_256_SHA
	[0032]	TLS_DHE_DSS_WITH_AES_128_SHA
	[0013]	SSL_DHE_DSS_WITH_3DES_EDE_SHA
	[0005]	SSL_RSA_WITH_RC4_128_SHA
	[0004]	SSL_RSA_WITH_RC4_128_MD5

Compression: 
	[00]	NO_COMPRESSION

**Comment by shawnmclean** [comment]
Could you give more context to the code? What does the method look like that you're calling from?

**Comment by MikeOtown** [comment]
This library is too difficult to debug - you provided no information on how I can figure out what's going on. No longer using this library.  Just using built-in .Net Framework Classes as documented here: http://www.codelocker.net/30405/c-sharp-send-a-mandrill-email-from-a-dot-net-website-or-application/
