### ISSUE TITLE
JSON error responses not shown when a MandrillException occurs

### ISSUE THREAD

**Issue by DennisHevener** [shawnmclean/Mandrill-dotnet#189]
When an exception occurs, the Mandrill error response is not shown in the default exception dump, so you have no idea what really happened.  For example "Invalid API key", etc.

You can get this yourself from the Error property of the Mandrill Exception of course, but I suggest changing this code in MandrillExceptions.cs as follows in order to put the Mandrill error in the InnerException:

From:
```
        public MandrillException(ErrorResponse error, string message)
 : base(message)
        {
            Error = error;
        }
```

To:
```
        public MandrillException(ErrorResponse error, string message)
 : base(message,  new Exception(error.Message))
        {
            Error = error;
        }
```

Now, you are never left wondering what went wrong!

Thanks for making Mandrill-dotnet available to us.

Dennis

**Comment by shawnmclean** [comment]
Thanks for the suggestion. 

Sorry this took so long, Had alittle trouble with the migration to .net core. Thats all sorted now so I'll work through these issues.

**Comment by shawnmclean** [comment]
Release in https://github.com/shawnmclean/Mandrill-dotnet/releases/tag/3.0.10
