### ISSUE TITLE
JSON.cs not used in MandrillApi.cs

### ISSUE THREAD

**Issue by ZentaSE** [shawnmclean/Mandrill-dotnet#198]
Hello!

Line 154 in MandrillApi.cs:
requestContent = JsonConvert.SerializeObject(data);

Shouldn't it be like this:
requestContent = JSON.Serialize(data);

Otherwise the settings set in JSON.cs like SnakeCaseNamingStrategy aren't included which results in wrong property names in the request. 

Or are we missing something?

**Comment by shawnmclean** [comment]
Hi @ZentaSE!

Is there something not being serialized correctly from/to Mandrill?

**Comment by ZentaSE** [comment]
Before changing it we got faulty requests against Mandrill because the properties had the wrong casing. 

For example   
"Message": {
Instead of:
  "message": {

We have our own fork of the project so we changed the above line and then it works great!
