### ISSUE TITLE
WebHookMessage

### ISSUE THREAD

**Issue by Pazkov** [shawnmclean/Mandrill-dotnet#201]
Hi all,
the WebHookMessage model has a wrong JsonProperty tag on the RawMsg property.

The tag is: 
[JsonProperty("raw_msg ")]

with a white space at the end... so the RawMsg Porperty is always null.

The repository seems to have removed the jsonproperty tags on oct 2017 bu the nugget package still has.

Can you check this?

Regards

**Comment by rhutchison** [comment]
This should be resolve https://github.com/shawnmclean/Mandrill-dotnet/commit/fcc977f29d111de29c5acb6b4557fa5b1f32981e#diff-29958293c812999370ef28c351a6ef8eL292
