### ISSUE TITLE
Question: Add CC addresses?

### ISSUE THREAD

**Issue by rpinna** [shawnmclean/Mandrill-dotnet#23]
I see bcc_address, to and from properties, but no cc: property.  Is there a way to add cc: address/display name pairs?

For the bcc_address property, does this support multiple email addresses (comma-separated)?  Does is support display name (e.g., "Fred Flinstone fflintstone@slate.com")?

Apologies for opening an issue, did not see a discussion forum.  Thanks for writing the wrapper, dropped in with ease.

**Comment by ventil8** [comment]
I am running 1.085 from Nuget should this new API support be included?
