### ISSUE TITLE
merge vars for Templates

### ISSUE THREAD

**Issue by malard** [shawnmclean/Mandrill-dotnet#40]
Is it possible to add support so that merge vars can be sent using "SendMessage" instead of or in addition to, "TemplateContent"? I only have one basic merge var in the template

_|CODE|_ and I can't seem to update it?

**Comment by Zapnologica** [comment]
I am confused now?

Cause what is the purpose of the `SendMessageTemplateRequest()` method.

It takes in Template Content as a 3rd parameter. However If I put my merge tag content in there, It does not replace it on the template.

I have to do the following:

       foreach (var item in variables)
            {
                emailMessage.AddRecipientVariable(item.emailAddress, item.Name, item.Content);
            }

Am I missing something?
