### ISSUE TITLE
 how to add attachments file docx, pdf.... to Mandrill

### ISSUE THREAD

**Issue by babyboypk** [shawnmclean/Mandrill-dotnet#68]
I am trying to add some attachments to an email that is being sent using the mandrill api via a Mandrill-dotnet wrapper. I have tried a number of different things to try to successfully attach the file but to no avail.

Who can give me some examples please attach the file by using the mandrill dot-net

**Comment by yogieputra8** [comment]
+1

**Comment by sheetu18** [comment]
I have link of pdf , Can we attach pdf through http link ?
