### ISSUE TITLE
Hoping for advice on how to use Mandrill-dotnet for bulk email

### ISSUE THREAD

**Issue by mdmoura** [shawnmclean/Mandrill-dotnet#74]
Hello,

I have an ASP.NET MVC 5 application where I need to send an HTML newsletter for about 80000 emails. I installed Mandrill-dotnet and I have a few questions:

1. Is it possible to use Mandrill templates and replace a few items on the template?
2. How would you send so many emails? Through the API correct?
    Would you add the emails to the TO List? How many by send?
3. How do you take care of the failed sending? My idea would be:

    Queue<String> emails = new Queue<String>();
    for each block of 200 emails {
      try {
         send
         remove the 200 emails from queue
      } catch (Exception) {
         log exception
      }   
    }

    Well, I am not sure the best way to do this?

4. Can you do this on an MVC action?
    I suppose I can't because the thread cannot be alive for so much time or am I wrong?
    How should I do this?

I appreciate if someone could advice me on out to do this with Mandrill-dotnet.

Thank You,
Miguel

**Comment by ctolkien** [comment]
@preguntoncojonero , as suggested by @sisve, use MailChimp for this scenario. Mandrill is not meant for newsletter style mailouts.
