### ISSUE TITLE
Mandrill.MandrillException "Post Failed"

### ISSUE THREAD

**Issue by digitaltouch** [shawnmclean/Mandrill-dotnet#88]
Cannot successfully make any API calls to Mandrill.  A "Post failed api/endpoint.json message is all the is given.  

Here is example code that is generating the error:

MandrillApi api = new MandrillApi("xxxxx-xxxx-xxxx-xxxx");
UserInfo info = api.UserInfo();

Can anyone point me in the right direction?

**Comment by shanebru** [comment]
I'm having the exact same issue!

**Comment by digitaltouch** [comment]
Have you checked that your API Key / Password combination is correct?  This
wound up being the issue for us.

I'm having the exact same issue!

**Comment by shanebru** [comment]
My API key was fine. The problem was I had a date in SendMessage which scheduled the send and this a paid for service in Mandrill. So I removed the date and everything works now.
