### ISSUE TITLE
Major breaking changes from v1.0.85 to v1.0.103

### ISSUE THREAD

**Issue by asbjornu** [shawnmclean/Mandrill-dotnet#98]
I just updated to the latest version of the Mandrill NuGet package and got compiler errors because stuff like `attachment` was renamed to `email_attachment`. Since NuGet versioning is based on [semantic versioning](http://semver.org/), such a change should incur a major version change, i.e. from `1.0` to `2.0`. If you want to simplify the process of versioning the package, I can recommend following [git-flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) or [github-flow](http://scottchacon.com/2011/08/31/github-flow.html) and adding [GitVersionTask](https://www.nuget.org/packages/GitVersionTask/) to the projects that need versioning.

If you want help with that, please let me know.

**Comment by shawnmclean** [comment]
I swore I responded to this by saying I'd love the help. Seems the email didn't go through.

I would gladly appreciate the help on how to handle the versioning.

**Comment by asbjornu** [comment]
Great, I'll see what I can do about this in a new branch and a pull-request.
