### ISSUE TITLE
The API is not very C# friendly

### ISSUE THREAD

**Issue by asbjornu** [shawnmclean/Mandrill-dotnet#99]
The API Mandrill dotnet exposes looks almost exactly like the API of the server-side, which is probably written in and for Ruby or Python. In C#, this looks alien and wrong. Classes like `email_attachment` should be named `EmailAttachment` and then it should be left up to the serializer to have this be seralized to `email_attachment`. Things like this can be configured with JSON.NET.

If you agree that this should be fixed and want help, please let me know.

**Comment by shawnmclean** [comment]
So I recently got some time to start on this task. Seems I have quite a few models to re-factor.

**Comment by asbjornu** [comment]
Looks good, @shawnmclean! I hope to find time to review this in Visual Studio soon, but from what I can tell here on GitHub, it looks like a very nice improvement! :)
